---
- hosts: 172.31.7.34
  become: yes
  tasks: 
  - name: git
    apt:
      name: git
      state: present
  - name: tree
    apt:
      name: tree
      statee: present
    ignore_errors: yes

  - name: wget
    apt: 
      name: wget
      state: present