---
- hosts: 172.31.7.34
  become: yes
  tasks: 
  - include: myplay.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
  - name: copy indexfile into node side
    copy:
      src: myindex
      dest: /var/www/html/index.html