---
- hosts: all
  become: yes
  tasks:
  - name: install openjdk on ubuntu nodes
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family=="Debain"
    
  - name: install openjdk on redhat nodes
    ansible.builtin.dnf:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"