---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on "RedHat" nodes
    ansible.builtin.dnf: 
         name: httpd
         state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start webserver on "RedHat" nodes
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat" 
 