---
- hosts: all
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
  - name: i want start git on ubuntu nodes
    service:
      name: git
      state: started 
