---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu nodes
    apt:
      name: "{{myansibleubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on ubuntu nodes
    service:
      name: "{{myansibleubuntu}}"
      state: started
    when: ansible_os_family=="Debian"
  - name: install webserver on "RedHat" nodes
    ansible.builtin.dnf: 
         name: "{{myansibleredhat}}"
         state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start webserver on "RedHat" nodes
    service:
      name: "{{myansibleredhat}}" 
      state: started
    when: ansible_os_family=="RedHat" 
 