---
- hosts: all
  become: yes
  tasks:
  - name: install webserver  on  ubuntu nodes
    apt:
      name: tree
      state: present
  - name: i  want start webserver on ubuntu nodes
    service:
        name: tree
        state: started 
